---

global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'docker0'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['docker0:9090']
  - job_name: 'node'
    static_configs:
      - targets:
        - docker0:9100
        - lxd-host:9100
