version: '3.3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - prometheus-data:/etc/prometheus/data
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor
    # ports:
    #   - "9090:9090"
    restart: always

  grafana:
    container_name: grafana
    depends_on:
      - prometheus
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor
    ports:
      - "3000:3000"
    restart: always

volumes:
  prometheus-data: {}
  grafana-storage: {}

networks:
  monitor: {}
