version: '3.3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.6.0
    volumes:
      - prometheus-data:/etc/prometheus/data
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor
    # ports:
    #   - "9090:9090"
    restart: always
    command:
      - '--storage.tsdb.retention=365d'
    extra_hosts:
      - "esc:10.92.124.1"

  grafana:
    container_name: grafana
    depends_on:
      - prometheus
    image: grafana/grafana:5.4.2
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor
    ports:
      - "3000:3000"
    restart: always

volumes:
  prometheus-data: {}
  grafana-storage: {}

networks:
  monitor: {}
