{
 "title": "overview",
 "description": "cpu, memory, network, disk graphs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"node\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu_seconds_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"user\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "user"
    },
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"system\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "system"
    },
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"iowait\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"softirq\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "softirq"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"node\",instance=~\"$node:$port\"} - node_memory_MemFree_bytes{job=\"node\",instance=~\"$node:$port\"}) / node_memory_MemTotal_bytes{job=\"node\",instance=~\"$node:$port\"} * 100",
     "legendFormat": "main"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node\",instance=~\"$node:$port\"} - node_memory_SwapFree_bytes{job=\"node\",instance=~\"$node:$port\"}) / node_memory_SwapTotal_bytes{job=\"node\",instance=~\"$node:$port\"} * 100",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"node\",instance=~\"$node:$port\"}[5m]))",
     "legendFormat": "transmit"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"node\",instance=~\"$node:$port\"}[5m]))",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{job=\"node\",instance=~\"$node:$port\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{job=\"node\",instance=~\"$node:$port\"}[5m]))",
     "legendFormat": "write"
    }
   ]
  }
 ]
}